### ISSUE TITLE
Bug when second matrix is singular

### ISSUE THREAD

**Issue by gboehl** [bnaecker/pygsvd#2] opened 2018-04-28 23:12 UTC
Hi and thanks for your good work! 

As many others I was roaming the internet for a straightforward implementation if GSVD in python, and I found it here. Unfortunately it does not really seem to work well. I was comparing with the octave package, (which does not nicely decompose the Sigma matrices in three blocks). It can be imported quite easily by using oct2py while having installed the linear-algebra package in octave. 

Here is a snip of code:

```
import numpy as np
from pygsvd import gsvd
from oct2py import octave as oc
oc.eval('pkg load linear-algebra')

A, B      = np.random.randint(0,10,18).reshape(2,3,3)
A[0] 	     = 0
B[:,1]     = 0

C, S, R, U, V, Q 	= gsvd(A,B, extras='uvq')
er1a 	= U.dot(C).dot(R).dot(Q.T) - A
er1b 	= V.dot(S).dot(R).dot(Q.T) - B
t1a 	= np.allclose(U.dot(C).dot(R).dot(Q.T), A)
t1b 	= np.allclose(V.dot(S).dot(R).dot(Q.T), B)

oc.push(['AA', 'BB'],[A, B])
oc.eval('[U, V, C, S, Q, R] 	= gsvd(AA,BB)')
U, V, c, s, Q, R 	= oc.pull(['U', 'V', 'C', 'S', 'Q', 'R'])
C 	= sl.block_diag(1,c)
S 	= np.block([[np.zeros((2,1)),s],[0,np.zeros((1,2))]])
er2a 	= U.dot(C).dot(R).dot(Q.T) 	- A
er2b 	= V.dot(S).dot(R).dot(Q.T) 	- B

print(t1a, t1b)
print(np.allclose(U.dot(C).dot(R).dot(Q.T), A), np.allclose(V.dot(S).dot(R).dot(Q.T), B))

print(np.sum(er1a))
print(np.sum(er1b))
print(np.sum(er2a))
print(np.sum(er2b))

```

**Comment by bnaecker** [comment] 2018-04-29 00:08
Hi Gregor,

It's nice to see that someone is interested in the package!

Can you describe in detail how the results differ from those in Octave? Are they entirely different, or slightly so? Do you also see the discrepancy between this package's implementation and Matlab's? And does Octave's results match those from Matlab?

To aid in tracking down any bugs, it would be very helpful if you could generate a completely reproducible example. In particular, explicitly write out the matrices that you used in your example, rather than generating them randomly, so that I can be sure to use the same inputs.

I should note a couple of things that may explain the discrepancies. First, Matlab's implementation sorts the singular values in opposite order from the method I've implemented here. This also means that columns of `U` and `V` will be in the reverse order. Looking at Octave's implementation, it's not clear to me how the singular values are sorted, so be sure to check that.

The second thing is that the columns of `U` and `V` returned by this package may differ from Octave's by a factor of `-1`. Furthermore, any number of the columns may differ this way, but they will differ in both `U` and `V`. That is, if column `U[:, i]` returned by this routine differs by a factor of `-1` from the corresponding column returned by Matlab's implementation, then column `V[:, i]` will also differ that way.

Hopefully we can track down any bug you might have found! Thanks!

**Comment by gboehl** [comment] 2018-04-29 08:17
Hi Benjamin,

Thanks for the quick reply!

I just mentioned the Octave example as it yields correct results. I have not tried Matlab since calling Matlab from within Python is not done as easily (and of course because Matlab is evil). You are entirely right that the matrices `Q`, `R`... might differ, but that is not important here because the decomposition should still return the original matrices. Btw., the Octave documentation for the function is not very helpful and to get a result like `S = diag(I,s,0)` from Octave requires further sorting as `s` seems to contain the zeroes on arbitrary positions. 

But back to the potential bug. Lets take this example:

```
A 	= np.array([[0, 0, 0],
       			[6, 4, 1],
       			[4, 0, 3]])

B 	= np.array([[3, 0, 1],
       			[8, 0, 2],
       			[8, 0, 5]])

C, S, R, U, V, Q 	= gsvd(A,B, extras='uvq')
```
Your docstring states that:

```
        U.T A Q = D_1 (0 R)
        V.T B Q = D_2 (0 R)
```
where I assume that `D_1 = C` and `D_2 = S` and everything is as in the GSVD wikipedia article. Hence `U.dot(C).dot(R).dot(Q.T)` should return `A` and `V.dot(S).dot(R).dot(Q.T)` should equal `B`.

However, while `np.allclose(U.dot(C).dot(R).dot(Q.T), A)` returns `True`, 
```
np.allclose(V.dot(S).dot(R).dot(Q.T), B)
```
is `False` with results deviating considerably from `B`.

Ps.:
It seems that your docstring contains another inaccuracy as you state
```
    R : ndarray
        The diagonalized matrix ``R``.
``` 
but `R` is (and should be) upper-triagular. This is of course minor :)

**Comment by bnaecker** [comment] 2018-04-30 14:14
I see the problem, but I'm not yet sure how to solve it. It seems the columns of `V` are not in the correct order.

Running the following:

    V_tmp = np.roll(V, 1, axis=1)
    np.allclose(V_tmp.dot(S).dot(R).dot(Q.T), B)

Should return `True`. So the returned array `V` is improperly sorted.

This error does not appear in other tests I've run, so I'm not sure the cause. It may have something to do with your chosen inputs being rank-deficient. But there is no mention of sorting `V` in any of the LAPACK documentation, regardless of the input ranks. I'll see if I can track down the cause, but let me know if you find it as well.

Thanks!

**Comment by bnaecker** [comment] 2018-04-30 22:04
Ok, I figured out the issue. I was not using the sorting information to correctly sort the returned arrays `U`, `V`, and `Q`. I didn't have extensive enough tests to uncover this situation.

I've started a patch, but it doesn't yet handle the rank-deficient case you've given here, which is indeed different from full-rank matrices. I'll get that working and push an update soon.

Thanks for bringing this to my attention.

**Comment by gboehl** [comment] 2018-04-30 23:29
I think I understood your problem. You assumed that LAPACK returns an `s` (the diagonal for the second matrix) that you could use like

```
S    = np.diag(np.zeroes(k),np.diag(s))
```
where `k` is `np.shape(B) - nl.matrix_rank(B)` (the number of dimensions missing for `B` to have full rank). Hence an S like
```
S    = [[ 0, 0 ],
          [ 0, s ]]
```
Where the zeroes stand for block matrices containing zeroes. However the LAPACK documentations states that `s` is supposed to be used like
```
S    = [[ 0, s ],
          [ 0, 0 ]]
``` 
I had the same problem with the Octave version of GSVD, where this is documented as above.

Luckily the fix is, as you have already suggested, to swap the corresponding rows in V:
```
V 	= V_temp.copy()
V[:,:k], V[:,k:] 	= V_temp[:,-k:], V_temp[:,:-k]
```
Doublechecking on wikipedia confirms that the way LAPACK provides the output is actually correct ("[S]...is non-negative block-diagonal, with diagonal blocks"), although I much more prefer your style because it is immediately applicable to the problem I am working with.

**Comment by gboehl** [comment] 2018-04-30 23:43
I also got the impression that you have to sort all the arrays according to your sorting of `C`:
```
tt 	= np.argsort(np.diag(C))[::-1]
U1, V1, C1, S1, (R1, Q1) 	= U1[:,tt], V1[:,tt], C1[tt][:,tt], S1[tt][:,tt], sl.rq(R1[tt].dot(Q1.T))
```
where `sl.rq` is the RQ-factorization from `scipy.linalg`. You must have done some sorting like this before somewhere in your code, but I have not had a look yet.

**Comment by bnaecker** [comment] 2018-05-01 02:09
Yes, I had originally used `s` as you suggested. My patch (in the works) does indeed swap the columns of `V` as you suggest. I did also implement a type of sorting, but not using `np.argsort()`. That method works when the matrices are full rank, but not for the rank-deficient inputs. Instead, I use the sorting information returned by the LAPACK routine.

I'm currently writing some more tests, I'll post the patch soon. Thanks for your help!

**Comment by bnaecker** [comment] 2018-05-01 03:07
Hi Gregor,

Check out the latest commit I just pushed. It should fix the problem you discovered. Play around with it, and let me know if you find any more issues.

Thanks!

**Comment by gboehl** [comment] 2018-05-02 12:12
Perfekt, it is also working with my (40x40) both sides rank-deficient matrices. Thanks a lot!

**Closed as completed** 2018-05-02 13:25 UTC
